In [5]:
#to write a python program to create an array and perform addition of two matrices using list and numpy arrays
import numpy as np
#Method 1: using list
matrix_a=[[1, 2, 3], [4, 5, 6], [6, 7, 8]]
matrix_b=[[8, 9, 7], [6, 5, 4], [3, 2, 1]]
result_list=[[matrix_a[i][j] + matrix_b[i][j] for j in range(len(matrix_a[0]))]
             for i in range(len(matrix_a))
            ]
print("List Addition Result:", result_list)

#Method 2: using Numpy Arrays
result_np= np.array(matrix_a)+np.array(matrix_b)
print("\nNumpy Addition result:\n", result_np)

List Addition Result: [[9, 11, 10], [10, 10, 10], [9, 9, 9]]

Numpy Addition result:
 [[ 9 11 10]
 [10 10 10]
 [ 9  9  9]]
